- name: Enable php 7.4
  shell: yum-config-manager --enable remi-php74 
  when: php_version == 74
  #in shell module we can provide any command, 
  #if we dont find some ansible modules
  #shell module doesnt check, it will just run, it doesnt care, do we already have some packages or not. it will always changed
  #ANSIBLE modules always check, do we installed something or not, if it's installed it doesn't do anything
- name: Enable php 7.3
  shell: yum-config-manager --enable remi-php73
  when: php_version == 73

- name: Enable php 7.2
  shell: yum-config-manager --enable remi-php72 
  when: php_version == 72

- name: install php
  yum: 
    name: "{{ php_packages }}"