- name: Download wordpress
  get_url:
    url: "{{ url }}"
    dest: "{{ destination }}"

- name: Extract wordpress   #with this module we extracted wordpress.tar.gz to folder wordpress (seenext module)
  unarchive:
    src: "{{ destination }}" #source of ansible vm \ after we putting remote_src:yes it becomes source of remote vm
    dest: /tmp                 #destination of remote vm
    remote_src: yes

- name: Copy file with owner and permissions
  copy:
    src: /tmp/wordpress/.   #. means everything, here we copied everything to the folder wordpress
    dest: /var/www/html
    owner: "{{ user }}"
    group: "{{ group }}"
    mode: '755'
    remote_src: yes

- name: Template a file to /var/www/html
  template:
    src: wp-config.php.j2 #j2 file is not only copying, it is replacing values, variables.
    dest: /var/www/html/wp-config.php

- name: restart service httpd #this module calls service
  service:
    name: httpd
    state: restarted   #to install wordpress bash script is easier, but we have to deploy in each vm, and with ansible we can deploy in many vms
  #at the interview we can say i can deploy with terraform and ansible wordpress and ....