- name: install mariadb
  yum:  #this module calls yum module
    name: 
      - mariadb
      - mariadb-server
    state: latest #it can be latest or present, version of httpd
  
- name: Start mariadb #this module calls service
  service:
    name: mariadb
    state: started
    enabled: yes

- name: Create a new database
  shell: mysql -e "create database IF NOT EXISTS {{ db_name }};"

- name: check user  #here we are checking if user exists
  shell: mysql -e "select 1 from mysql.user where user = '{{ db_user }}';" | grep -q 1
  register: user_check
  ignore_errors: yes 

- name: create user
  shell: mysql -e "CREATE USER {{ db_user }}@localhost IDENTIFIED BY '{{ db_password }}';" 
  when: user_check.rc != 0 #we executing this task if user exist

- name: grant privileges
  shell: mysql -e "GRANT ALL PRIVILEGES ON {{ db_name }}.* TO {{ db_user }}@localhost IDENTIFIED BY '{{ db_password }}';"

- name: Flush privileges
  shell: mysql -e "FLUSH PRIVILEGES;" 

# - name: anyname
#   shell: "{{ item }}"
#   loop:
#     - echo hello
#     - mkdir test 
#     - touch kaizen  #or we can do echo hello && mkdir test etc